### ISSUE TITLE
Display multiple images in slideshow

### ISSUE THREAD

**Issue by MartyNZ** [2sic/app-news#11]
I'm testing this App and would like this functionality if possible.

Is it possible to upload multiple images for a story so they can be displayed in a slideshow for the story?

1. in the edit UI is it possible to use a multi-select for uploading images? (a maximum of 3)
2. to then use in a foreach function to create the slideshow.
3. I would also like to be able to have a caption available for each image.

TIA

MartyNZ

**Comment by iJungleboy** [comment]
The typical solution for this is to use Inner-Content. Just add a Swiper-App or something into the content and you're all set :).
