### ISSUE TITLE
Misspelling and a Missed Using?

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/app-news#24]
Looks like (if needed) .Services is misspelled in [line 4, bs5/_Details.cshtml](https://github.com/2sic/app-news/blob/4101864e3d6312e6658e643065f0a5582192ccdc/bs5/_Details.cshtml)
 
Should BS3 still be using .RazorComponent or .Razor14 on [line 1, bs3/_Details.cshtml](https://github.com/2sic/app-news/blob/4101864e3d6312e6658e643065f0a5582192ccdc/bs3/_Details.cshtml)

**Comment by iJungleboy** [comment]
@getBlup could you check?
