### ISSUE TITLE
News details not visible for all user

### ISSUE THREAD

**Issue by bash862** [2sic/app-news#7]
DNN V. 9.6.2
2sic_2SexyContent_11.04.00
2sxcApp_News_4.1.1

I installed all the last version fo the 2SexyContent and tha App News; after installation I configured the app for user the correct page od the details, but when I open the site with no logged-in users, they can see the list of the news but when go to the details page of each news, appear the error that can't found the article; when I do the same things with the host user of DNN I can see the details of the news. If, in the page where I put the news app, I give the EDIT permission to All user I can see the details. 
Why is not possible for all user, with only view permission on the page, to see the details of the News?
thanks

**Comment by iJungleboy** [comment]
@bash862 this is unusual - we use the news app in many places and haven't had this before. 

My guess is you did something very strange with permissions, or that you have created news that isn't published yet (so it's filtered out for normal users).

**Comment by iJungleboy** [comment]
I think I found the culprit

If news items are published in future, the details page doesn't show them to normal users, but I think the list still has a minor bug where they are not always filtered out. So that's probably why it shows in the list (even though it shouldn't) but the details then hides it. 

Can you check?

**Comment by bash862** [comment]
@iJungleboy  thanks for the answer: I tested and the problem is exactly the date of visibility. In my case the news that I created have the main date set to today or a past date but didn't have a date for the field "Show from" of the visibility. In this case the news appear in the list but the normal user can't see the details of the news.
If I put a corerct date in the field "Show from" the normal users can see the details too. 
So there is little bug if create a news with the main date (not published in future) and the field "Show from", in the visibility area, is not seted.
Many thanks for the support!

**Comment by iJungleboy** [comment]
@ropalko could you look into this? I may have already fixed it a few weeks ago, but I'm not sure...

**Comment by ropalko** [comment]
@iJungleboy You still have to fill in the "Show From" field to make the detail view work correctly for unregistered users. So it is not fixed yet

**Comment by iJungleboy** [comment]
@ropalko do I have to do something, or do you need to update the news app?

**Comment by jeremy-farrance** [comment]
I think I figured this out. When users are not logged in, the Query for News Detail includes a filter for "no future news". But when the ShowFrom field is left blank, that filter returns false. Simply setting the ShowFrom date to the same as the Date (or any date in the past) fixes it so the news item shows. So either the Query needs a fix or the filter needs a way to be true "null <= DateTime:Now" 

To see this in action, simply make a copy of the Query: News Detail. Then
- make sure your Test Params' UrlKey is selecting an actual article
- verify that article has a past date in the Visibility/ShowFrom field
- change ShowDrafts to false
- now Run - you SHOULD SEE the article
- now (in another window) edit the article
- delete the contents of the Visibility/ShowFrom field
- save
- now Run the query and you will NOT get the article

**Comment by jeremy-farrance** [comment]
Bump?

**Comment by jeremy-farrance** [comment]
Bump?

**Comment by jeremy-farrance** [comment]
I played some more and to rephrase, this is easy to fix by adjusting your data. Simply put, ShowFrom and ShowTo need at least 1 Entity in the List (including a category applied) to not be empty/null. So the fastest fix is to make sure at least 1 News item has every category. Then all your news items will show to the public (people not logged in).

**Comment by bash862** [comment]
Sorry for the late. The last workaround that you wrote is working perfectly.  Sorry but the other solution i can't test, beccause i'm focussed in another project. I think you can close this problem beccause the last solution it's perfect! 
Many thanks for the support!

**Comment by TopCat6** [comment]
I have tried that work-around and cannot get it to work. For 1 News item, I added a start and end Visibility date and then created a Category and set it to that. Still, any other News item that did not have a Visibility start date set (and no end date) would show the teaser image and text, but when you click, you get the Article Not Found page.

There is an inconsistency with showing the teaser with a "Read More" link when the Visibility date is unspecified. Either the full article should also be available under that condition, or the teaser should not be visible. If you can see the teaser as a non-registered user, you should be able to get to the article detail.  This is the way the DNN HTML module works... if you do not specify a start-date, the module content **is visible**.

Sure, it is likely low priority, but I feel it should be self-consistent.

**Comment by ropalko** [comment]
fixed since version [News V5.2 Hybrid](https://github.com/2sic/app-news/releases/tag/v05.02.00)
