### ISSUE TITLE
News categories filter

### ISSUE THREAD

**Issue by bash862** [2sic/app-news#8]
DNN V. 9.6.2
2sic_2SexyContent_11.2.0
2sxcApp_News_4.1.1

In the news app, when I select the list view (the view is standard without personalizazion) and when the news created have more then one category, in the top of the module appear the button categories filter; the problem is that these buttons work only for the user that have the EDIT permission in the page; if a user, that have only the VIEW permission, click in one button to filter for a category, all the article disappear (if click on the All button all the article are showed).
Can you check the problem?
Thanks

**Comment by iJungleboy** [comment]
@ropalko can you verify? I think this is runinng on many websites, so this woudl be strange...

**Comment by bash862** [comment]
the same thing happen when, in the viewconfiguration, I select a category to show only the items of that category.

**Comment by bash862** [comment]
Another similar problem connected with the user permission: if I delete the 3 demo items and create new items, the new items is visible only for the user with Edit permission; but instead, if I don't delete the demo items and create new items, these are visible from all users of DNN.

**Comment by bash862** [comment]
I think I have identified where the problem is: the "News List" query has a "News without expiration" filter that checks if an entry has the "ShowTo" field empty; but if, in the list of elements, no one has the ShowTo field set, the query returns 0 elements; in i have set this field for at least one item and the query returns the correct field number. Can you check this query?
Thank you

**Comment by jeremy-farrance** [comment]
I added details and steps to reproduce [over here](https://github.com/2sic/app-news/issues/7#issuecomment-763029948)
https://github.com/2sic/app-news/issues/7#issuecomment-763029948

**Comment by ropalko** [comment]
fixed since version [News V5.2 Hybrid](https://github.com/2sic/app-news/releases/tag/v05.02.00)
